### ISSUE TITLE
Determine best OSRM API to use for trip calcuation

### ISSUE THREAD

**Issue by natedunn2230** [Optimize-The-Drive/optimize-the-drive#43]
Turns out we probably don't need to run the distance matrix on all combinations of the trip points, and then have the genetic algorithm re-order the points. We can probably call a native trip or table api within the OSRM service to return the points in order for us (depending on origin and destination points)

Check out: http://project-osrm.org/docs/v5.7.0/api/#requests

**Comment by XarosElite** [comment]
We have decided on the trip API under the OSRM service
